[project]
name = "swin-fire-3d"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "einops>=0.8.0",
    "lightning>=2.5.0.post0",
    "timm>=1.0.14",
    "torch>=2.5.1",
]
