max_epochs: 100
accelerator: gpu
devices: 1
precision: 16-mixed
strategy: auto
fast_dev_run: false
accumulate_grad_batches: 4
profiler: simple

logger:
  enabled: true
  dir: logs/            # Directory to save logs
  name: swin_hidden144_lr3e-4   # Name for the logger
  default_hp_metric: false

callbacks:
  early_stopper:
    enabled: true
    monitor: val_loss   # Metric to monitor
    patience: 5        # Number of epochs to wait for improvement
    mode: min           # Options: 'min' or 'max'
    min_delta: 0.01    # Minimum change to qualify as an improvement

  image_logger:
    enabled: true       # Enable logging of image predictions

  logging_callback:
    enabled: false       # Enable average loss per epoch log

  final_metrics_callback:
    enabled: true
    on_training_data: false
    on_validation_data: true

  learning_rate_monitor:
    enabled: true
